### ISSUE TITLE
bug: search does not work

### ISSUE THREAD

**Issue by HagenBeelitz** [AfeefaDe/afeefa-backend-ui#123]
exception: "undefined method `arel_table' for nil:NilClass", backtrace: [,…]

**Comment by stevereinke** [comment]
this is caused by enabling of caching
can be reproduced by unskipping test 'get todos default filter and sort'
will be solved by refactoring orga and event models to subclass of entry
can be workarounded by adding a '#' before 'config.resource_cache = Rails.cache' in config/initializers/jsonapi_resource.rb:7

**Comment by stevereinke** [comment]
workaround comitted
